apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: mern-app
  annotations:
    # Specify which Ingress Controller to use
    kubernetes.io/ingress.class: nginx
    
    # cert-manager annotations for automatic certificate management, using the ClusterIssuer defined earlier. Will also complete the http-01 challenge for me automatically
    cert-manager.io/cluster-issuer: letsencrypt-prod
    
    # nginx-specific annotations, If someone visits http://mern.ak-cloudtechdigital-az.info, they'll be redirected to https://mern.ak-cloudtechdigital-az.info
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  # Use ingressClassName field instead of annotation (Kubernetes 1.18+)
  ingressClassName: nginx
  # TLS configuration
  tls:
  - hosts:
    - mern.ak-cloudtechdigital-az.info
    secretName: mern-tls-secret  # cert-manager will create this secret
  
  # Routing rules
  rules:
  - host: mern.ak-cloudtechdigital-az.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80